version: "3.7"
services:
    app:
        image: "node:14.18"
        container_name: "vt-admin-app"
        working_dir: /app
        command: /bin/bash -c "npm install -g pnpm && pnpm install && pnpm serve"
        ports:
            - "50000:50000"
        volumes:
            - ./:/app
            - $HOME/.npm:/root/.npm
            - $HOME/Library/pnpm:/root/pnpm
        restart: unless-stopped
        environment:
            - HOST=0.0.0.0
            - TZ=Asia/Shanghai
            - XDG_DATA_HOME=/root
